export const env = {
    host: "0.0.0.0",
    ssl: false,
    ssl_cert: "",
    ssl_key: "",
    ssl_port: 443,
    port: 8080,
    log_interval: 5,
    maximum_log_age: 10080,
    cleanup_interval: 15,
    redis_path: null,
    redis_host: "127.0.0.1",
    redis_port: 6379,
    redis_auth: null,
    redis_tls: null,
    frontend_user: "user",
    frontend_password: "password",
    backend_user: "user",
    backend_password: "password",
    server_health: {
        servers: [],
        keep_registered: true,
        error_message_threshold: 5,
        error_message_threshold_time: 5,
        ram_usage_threshold: 0.8,
        ram_usage_threshold_time: 10,
        cpu_usage_total_threshold: 0.9,
        cpu_usage_single_threshold: 0.85,
        cpu_usage_threshold_time: 5,
        memory_usage_threshold: 0.8,
        memory_usage_threshold_time: 15,
        timeout: 2500,
    }
}